language: node.js
node_js:
  - '10'
before_install:
  - npm install -g @angular/cli
install: npm install
branches:
  only:
    - master
deploy:
  provider: heroku
  app: final-angular-project
  api_key:
    secure: f3e27d03-2675-468d-b66b-54ef96916423
